// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD06oeLlZvZnMAJ53bK-o6hDSbMX-PVU2o',
    appId: '1:1004349335287:web:6a59337269b35f34ba15f2',
    messagingSenderId: '1004349335287',
    projectId: 'nganjuk-abirupa',
    authDomain: 'nganjuk-abirupa.firebaseapp.com',
    storageBucket: 'nganjuk-abirupa.firebasestorage.app',
    measurementId: 'G-1WX12PS918',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb78F7vv7iripzp-ViEj_XBK6yqPCbWeI',
    appId: '1:1004349335287:android:c39e924f68d0fb7fba15f2',
    messagingSenderId: '1004349335287',
    projectId: 'nganjuk-abirupa',
    storageBucket: 'nganjuk-abirupa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbIvPU3YcvVSj1c7niI_eO1uyQyFXzREo',
    appId: '1:1004349335287:ios:d302ca43ea70006fba15f2',
    messagingSenderId: '1004349335287',
    projectId: 'nganjuk-abirupa',
    storageBucket: 'nganjuk-abirupa.firebasestorage.app',
    androidClientId: '1004349335287-32518tobrns9udlgkj33v4p3e1m2fcjq.apps.googleusercontent.com',
    iosClientId: '1004349335287-kgia6lk8al2pe77624bgdt30eunsc9go.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngajukAbirupa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbIvPU3YcvVSj1c7niI_eO1uyQyFXzREo',
    appId: '1:1004349335287:ios:d302ca43ea70006fba15f2',
    messagingSenderId: '1004349335287',
    projectId: 'nganjuk-abirupa',
    storageBucket: 'nganjuk-abirupa.firebasestorage.app',
    androidClientId: '1004349335287-32518tobrns9udlgkj33v4p3e1m2fcjq.apps.googleusercontent.com',
    iosClientId: '1004349335287-kgia6lk8al2pe77624bgdt30eunsc9go.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngajukAbirupa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ7Je5ZTCLqqQLGT34HqukJFudS77mn40',
    appId: '1:1004349335287:web:fd53446a81f103fbba15f2',
    messagingSenderId: '1004349335287',
    projectId: 'nganjuk-abirupa',
    authDomain: 'nganjuk-abirupa.firebaseapp.com',
    storageBucket: 'nganjuk-abirupa.firebasestorage.app',
    measurementId: 'G-MYYH6MMQN0',
  );
}
